version: '2'
services:
  hadoop001:
    image: lasbun/hadoop2.7.2:0.0.1
    ports:
      - "10022:22"
      - "50710:50070"
      - "18088:8088"
    hostname: hadoop001
    networks: 
      static-network:
        ipv4_address: 10.5.0.101
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

networks:
  static-network:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.100